server {
    listen 80;
    server_name localhost;

    root /app/public;
    index index.php;

    # ── Logs ────────────────────────────────────────────────────────
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # ── Upload size ─────────────────────────────────────────────────
    client_max_body_size 5m;

    # ── Gzip ────────────────────────────────────────────────────────
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    # ── Symfony front controller ─────────────────────────────────────
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # ── PHP-FPM (app:9000) ───────────────────────────────────────────
    location ~ ^/index\.php(/|$) {
        fastcgi_pass app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT   $realpath_root;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        internal;
    }

    # ── Bloquer les autres .php ──────────────────────────────────────
    location ~ \.php$ {
        return 404;
    }
}
